# This file is part of App3 (http://code.google.com/p/app3).
# 
# Copyright (C) 2009 JJ Geewax http://geewax.org/
# All rights reserved.
# 
# This software is licensed as described in the file COPYING.txt,
# which you should have received as part of this distribution.

application: my_sample_app
version: 1
runtime: python
api_version: 1

handlers:
- url: .*
  script: main.py
